### PR TITLE
feat(HACBS-2425): remove bundles dockerfile

### PR DESCRIPTION
**Pull request by Troy876**
Bundles Dockerfile is replaced by Utils Dockerfile. GH action dockerfile_push.yaml has been removed.
Latest version of tasks using base-image migrated to utils-image.

### CODE REVIEW

**Review by scoheb — APPROVED** [review]

**Review by mmalina — APPROVED** [review]
Approved. But what is "depreciate" ;) (I know the word, but haven't seen it in this context.) Didn't you mean "deprecate"? But that's usually used when you keep something, but discourage usage (and prepare for removal later). Here we're removing it right away. So why not just say "remove"?

**Review by davidmogar — APPROVED** [review]

**Comment by Troy876** [comment]
> Approved. But what is "depreciate" ;) (I know the word, but haven't seen it in this context.) Didn't you mean "deprecate"? But that's usually used when you keep something, but discourage usage (and prepare for removal later). Here we're removing it right away. So why not just say "remove"?

I only just realised that I used the wrong word but you make a point, "remove" is a lot simpler and doesn't cause confusion like this lol

**Comment by mmalina** [comment]
> I only just realised that I used the wrong word but you make a point, "remove" is a lot simpler and doesn't cause confusion like this lol

Cool, thanks. Can you also change it in the commit message, please?

**Comment by johnbieren** [comment]
> > I only just realised that I used the wrong word but you make a point, "remove" is a lot simpler and doesn't cause confusion like this lol
> 
> Cool, thanks. Can you also change it in the commit message, please?

Yeah, depreciate would be to lessen in value

**Pull request merged**
