### PR TITLE
feat(HACBS-2304): add verify_ec_task_bundle parameter to pipelines

### PR DESCRIPTION
**Pull request by johnbieren**

### CODE REVIEW

**Comment by johnbieren** [comment]
Depends on https://github.com/redhat-appstudio/release-service/pull/205

**Comment by johnbieren** [comment]
```
$ diff -r deploy-release/
0.1/    0.2/    0.3/    OWNERS  
[jbieren@jbieren pipeline]$ diff -r deploy-release/0.2 deploy-release/0.3
diff -r deploy-release/0.2/deploy-release.yaml deploy-release/0.3/deploy-release.yaml
7c7
<     app.kubernetes.io/version: "0.2"
---
>     app.kubernetes.io/version: "0.3"
20a21,23
>     - name: verify_ec_task_bundle
>       type: string
>       description: The location of the bundle containing the verify-enterprise-contract task
27c30
<             value: quay.io/hacbs-contract/ec-task-bundle:snapshot
---
>             value: $(params.verify_ec_task_bundle)
diff -r deploy-release/0.2/README.md deploy-release/0.3/README.md
10a11,15
> | verify_ec_task_bundle | The location of the bundle containing the verify-enterprise-contract task | No | - |
> 
> ### Changes since 0.2
> - the verify_ec_task_bundle parameter was added
>     - with this addition, the verify-enterprise-contract task version is no longer static
15c20
< bundles resolver is used with new format.
\ No newline at end of file
---
> bundles resolver is used with new format.
diff -r deploy-release/0.2/samples/sample_release_PipelineRun.yaml deploy-release/0.3/samples/sample_release_PipelineRun.yaml
11a12,13
>     - name: verify_ec_task_bundle
>       value: ""
16c18
<         value: quay.io/hacbs-release/pipeline-deploy-release:0.2
---
>         value: quay.io/hacbs-release/pipeline-deploy-release:0.3
diff -r deploy-release/0.2/tests/run.yaml deploy-release/0.3/tests/run.yaml
11a12,13
>     - name: verify_ec_task_bundle
>       value: ""
16c18
<         value: quay.io/hacbs-release/pipeline-deploy-release:0.2
---
>         value: quay.io/hacbs-release/pipeline-deploy-release:0.3
```

**Comment by johnbieren** [comment]
```
$ diff -r fbc-release/0.10 fbc-release/0.11
diff -r fbc-release/0.10/fbc-release.yaml fbc-release/0.11/fbc-release.yaml
7c7
<     app.kubernetes.io/version: "0.10"
---
>     app.kubernetes.io/version: "0.11"
58a59,61
>     - name: verify_ec_task_bundle
>       type: string
>       description: The location of the bundle containing the verify-enterprise-contract task
72c75
<             value: quay.io/hacbs-contract/ec-task-bundle:snapshot
---
>             value: $(params.verify_ec_task_bundle)
diff -r fbc-release/0.10/README.md fbc-release/0.11/README.md
20a21
> | verify_ec_task_bundle | The location of the bundle containing the verify-enterprise-contract task | No | - |
22a24,27
> 
> ### Changes since 0.10
> - the verify_ec_task_bundle parameter was added
>     - with this addition, the verify-enterprise-contract task version is no longer static
diff -r fbc-release/0.10/samples/sample_release_PipelineRun.yaml fbc-release/0.11/samples/sample_release_PipelineRun.yaml
29a30,31
>     - name: verify_ec_task_bundle
>       value: ""
34c36
<         value: quay.io/hacbs-release/pipeline-fbc-release:0.10
---
>         value: quay.io/hacbs-release/pipeline-fbc-release:0.11
diff -r fbc-release/0.10/tests/run.yaml fbc-release/0.11/tests/run.yaml
29a30,31
>     - name: verify_ec_task_bundle
>       value: ""
34c36
<         value: quay.io/hacbs-release/pipeline-fbc-release:0.10
---
>         value: quay.io/hacbs-release/pipeline-fbc-release:0.11
```

**Comment by johnbieren** [comment]
```
$ diff -r push-to-external-registry/0.10 push-to-external-registry/0.11
diff -r push-to-external-registry/0.10/push-to-external-registry.yaml push-to-external-registry/0.11/push-to-external-registry.yaml
7c7
<     app.kubernetes.io/version: "0.10"
---
>     app.kubernetes.io/version: "0.11"
58a59,61
>     - name: verify_ec_task_bundle
>       type: string
>       description: The location of the bundle containing the verify-enterprise-contract task
115c118
<             value: quay.io/hacbs-contract/ec-task-bundle:snapshot
---
>             value: $(params.verify_ec_task_bundle)
diff -r push-to-external-registry/0.10/README.md push-to-external-registry/0.11/README.md
20a21,25
> | verify_ec_task_bundle | The location of the bundle containing the verify-enterprise-contract task | No | - |
> 
> ### Changes since 0.10
> - the verify_ec_task_bundle parameter was added
>     - with this addition, the verify-enterprise-contract task version is no longer static
diff -r push-to-external-registry/0.10/samples/sample_push-to-external-registry_PipelineRun.yaml push-to-external-registry/0.11/samples/sample_push-to-external-registry_PipelineRun.yaml
25a26,27
>     - name: verify_ec_task_bundle
>       value: ""
30c32
<         value: quay.io/hacbs-release/pipeline-push-to-external-registry:0.10
---
>         value: quay.io/hacbs-release/pipeline-push-to-external-registry:0.11
diff -r push-to-external-registry/0.10/tests/run.yaml push-to-external-registry/0.11/tests/run.yaml
25a26,27
>     - name: verify_ec_task_bundle
>       value: ""
30c32
<         value: quay.io/hacbs-release/pipeline-push-to-external-registry:0.10
---
>         value: quay.io/hacbs-release/pipeline-push-to-external-registry:0.11
```

**Comment by johnbieren** [comment]
```
$ diff -r release/0.13 release/0.14
diff -r release/0.13/README.md release/0.14/README.md
15a16,20
> | verify_ec_task_bundle | The location of the bundle containing the verify-enterprise-contract task | No | - |
> 
> ### Changes since 0.13
> - the verify_ec_task_bundle parameter was added
>     - with this addition, the verify-enterprise-contract task version is no longer static
diff -r release/0.13/release.yaml release/0.14/release.yaml
7c7
<     app.kubernetes.io/version: "0.13"
---
>     app.kubernetes.io/version: "0.14"
40a41,43
>     - name: verify_ec_task_bundle
>       type: string
>       description: The location of the bundle containing the verify-enterprise-contract task
97c100
<             value: quay.io/hacbs-contract/ec-task-bundle:cf58b68b872dacbbcb2cc571efac135b2989d638
---
>             value: $(params.verify_ec_task_bundle)
diff -r release/0.13/samples/sample_release_PipelineRun.yaml release/0.14/samples/sample_release_PipelineRun.yaml
19a20,21
>     - name: verify_ec_task_bundle
>       value: ""
24c26
<         value: quay.io/hacbs-release/pipeline-release:0.13
---
>         value: quay.io/hacbs-release/pipeline-release:0.14
diff -r release/0.13/tests/run.yaml release/0.14/tests/run.yaml
19a20,21
>     - name: verify_ec_task_bundle
>       value: ""
24c26
<         value: quay.io/hacbs-release/pipeline-release:0.13
---
>         value: quay.io/hacbs-release/pipeline-release:0.14
```

**Review by mmalina — APPROVED** [review]

**Pull request merged**
